#!/bin/bash
#
# artcloud_scheduler
#
# chkconfig: - 60 50
# description: The art cloud scheduler does things like periodically cleanup heartbeats
# processname: scripts/scheduler.py

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
prog="scheduler.py"

ART_CLOUD_SRC_DIR="/webapp/art-cloud/art_cloud"
SCHEDULER_SCRIPT_PATH="$ART_CLOUD_SRC_DIR/scripts/scheduler.py"

start() {
	export PYTHONPATH=.
	cd $ART_CLOUD_SRC_DIR
        daemon $SCHEDULER_SCRIPT_PATH &
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
        echo
        return $RETVAL
}

stop() {
        echo -n $"Shutting down $prog: "
        killproc $prog
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
        return $RETVAL
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        RETVAL=$?
        ;;
  condrestart)
        if [ -f /var/lock/subsys/$prog ]; then
            stop
            start
            RETVAL=$?
        fi
        ;;
  status)
        status $prog
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|condrestart|status}"
        exit 2
esac

exit $RETVAL
